/**
 * server/services/scorer.js
 *
 * Deterministic B2B SaaS fit scorer. Computes a numeric fit score (0–100)
 * from the structured analysis object produced by the Claude analyzer. The
 * scoring logic is entirely rule-based — no LLM is involved — so results are
 * reproducible and auditable. Each positive or negative signal is captured and
 * returned alongside the score so the frontend can display a rationale list.
 *
 * The rationale text itself is generated by Claude in analyzer.js; this module
 * only produces the numeric value, the label, and the signal arrays.
 */

/**
 * Computes a B2B SaaS fit score from a structured analysis object. Points are
 * awarded for signals that indicate a company is a strong candidate for B2B
 * SaaS tooling: B2B business model, product-led growth motion, pricing page,
 * integrations ecosystem, active blog, demo CTA, freemium offering, careers
 * page, multilingual reach, and software/SaaS sector classification. The
 * company's estimated size and sector are also considered. Returns an object
 * containing the numeric value (0–100), a human-readable label, and two
 * arrays listing the signals that contributed positively and negatively to the
 * score.
 */
export function score(analysis) {
  const { company, tech_stack, gtm_signals } = analysis
  const positive = []
  const negative = []
  let value = 0

  if (company?.business_model?.toLowerCase().includes('b2b')) {
    value += 20
    positive.push('B2B business model')
  }

  if (gtm_signals?.product_led) {
    value += 15
    positive.push('Product-led growth')
  }

  if (gtm_signals?.has_pricing_page) {
    value += 10
    positive.push('Pricing page detected')
  }

  if (gtm_signals?.integrations_page) {
    value += 10
    positive.push('Integrations page')
  }

  if (gtm_signals?.blog_active) {
    value += 8
    positive.push('Active blog')
  }

  if (gtm_signals?.demo_cta) {
    value += 8
    positive.push('Demo CTA present')
  }

  if (gtm_signals?.free_trial_or_freemium) {
    value += 8
    positive.push('Free trial or freemium')
  }

  if (gtm_signals?.has_careers_page) {
    value += 5
    positive.push('Careers page (growth signal)')
  }

  if (gtm_signals?.multilingual) {
    value += 5
    positive.push('Multilingual (global reach)')
  }

  // SMB and mid-market companies tend to have shorter sales cycles than
  // enterprise accounts, which makes them more attractive prospects.
  const size = company?.estimated_size?.toLowerCase() || ''
  if (size.includes('smb') || size.includes('mid-market')) {
    value += 5
    positive.push('SMB/Mid-market size (faster sales cycle)')
  } else if (size.includes('enterprise') || size.includes('large')) {
    negative.push('Enterprise size may mean long sales cycles')
  }

  const sector = company?.sector?.toLowerCase() || ''
  if (sector.includes('saas') || sector.includes('software') || sector.includes('tech')) {
    value += 6
    positive.push('Software/SaaS sector')
  }

  // Clamp to the valid 0–100 range in case future signal additions overshoot.
  value = Math.min(100, Math.max(0, value))

  let label
  if (value <= 30) label = 'Weak fit'
  else if (value <= 55) label = 'Moderate fit'
  else if (value <= 75) label = 'Good fit'
  else label = 'Strong fit'

  return { value, label, signals_positive: positive, signals_negative: negative }
}
